name: C++ CI with Catch2

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ccache

      - name: Cache FetchContent dependencies
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: ${{ runner.os }}-fetchcontent-${{ hashFiles('CMakeLists.txt', 'linalg_cpp/tests/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-fetchcontent-

#      - name: Configure CMake
#        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_BINDING=OFF

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_BINDING=OFF \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Build tests
        run: cmake --build build --target linalg_tests --parallel

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure

